// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xddunzaxllqgresvuryx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkZHVuemF4bGxxZ3Jlc3Z1cnl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDkzNzYsImV4cCI6MjA3MjcyNTM3Nn0.SmBVhQi9UP_xaLcIyeIIncvSjvZjFNwqxbY3ZchdEG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});